name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 30 minutes
  workflow_dispatch:          # Allow manual trigger if needed

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://personalfinancetracker-xspuydxzewkphfpyqqcckd.streamlit.app/
